apiVersion: gateway.networking.k8s.io/v1                                                                                                                                                         
kind: HTTPRoute                                                                  
metadata:                                                                        
  name: animated-buble-httproute                                                      
spec:                                                                            
  parentRefs:                                                                    
  - group: gateway.networking.k8s.io                                             
    kind: Gateway                                                                
    name: traefik-gateway                                                        
    namespace: traefik-v2                                                        
  rules:                                                                         
  - backendRefs:                                                                 
    - group: ""                                                                  
      kind: Service                                                              
      name: webserver-svc                                                        
      namespace: default                                                         
      port: 8080                                                                 
      weight: 1                                                                  
    filters:                                                                     
    - type: URLRewrite                                                           
      urlRewrite:                                                                
        path:                                                                    
          replacePrefixMatch: /                                                  
          type: ReplacePrefixMatch                                               
    matches:                                                                     
    - path:                                                           
      type: PathPrefix
      value: /animated-bubble
