apiVersion: gateway.networking.k8s.io/v1                                                                                                                                                         
kind: HTTPRoute                                                                  
metadata:                                                                        
  name: bubble-animation-httproute
  namespace: poc-ns
spec:                                                                            
  parentRefs:                                                                    
  - group: gateway.networking.k8s.io                                             
    kind: Gateway                                                                
    name: traefik-gateway                                                        
    namespace: traefik-v2                                                        
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /bubble-app
    filters:
    - type: RequestRedirect
      requestRedirect:
        path:
          type: ReplaceFullPath
          replaceFullPath: /
        statusCode: 308
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
      - kind: Service
        name: bubble-animation-svc
        namespace: poc-ns
        port: 8080
        weight: 1
